{"Log_Time": "2024-04-13 13:19:54,309", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "170", "FuncName": "Recommendation", "Message": "15 recommendations generated for Apocalypse Now (1979) successfully!"}
{"Log_Time": "2024-04-13 13:25:28,506", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "170", "FuncName": "Recommendation", "Message": "15 recommendations generated for Apocalypse Now (1979) successfully!"}
{"Log_Time": "2024-04-13 13:25:41,881", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "251", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 33"}
{"Log_Time": "2024-04-13 13:25:50,565", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "251", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 21"}
{"Log_Time": "2024-04-13 13:28:37,487", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "251", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 11"}
{"Log_Time": "2024-04-13 13:34:39,260", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "170", "FuncName": "Recommendation", "Message": "15 recommendations generated for Toy Story (1995) successfully!"}
{"Log_Time": "2024-04-13 14:21:03,681", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "257", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 11"}
{"Log_Time": "2024-04-13 14:28:30,357", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "260", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 11"}
{"Log_Time": "2024-04-13 14:28:42,800", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "260", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 11"}
{"Log_Time": "2024-04-13 14:45:59,142", "Levelname": "ERROR", "Filename": "recommender.py", "Module": "recommender", "Lineno": "256", "FuncName": "Recommendation", "Message": "Error occured while calculating title recommendation for 11: ('KeyError', \"Column(s) ['timestamp'] do not exist\")\nTraceback (most recent call last):\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\ML-Projects\\Movie_Recommender_System\\Recommenders\\recommender.py\", line 242, in get_similar_users\n    user_ratings = similar_user_movies.groupby('title').agg({'rating': 'mean',\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\groupby\\generic.py\", line 1271, in aggregate\n    result = op.agg()\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\apply.py\", line 163, in agg\n    return self.agg_dict_like()\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\apply.py\", line 403, in agg_dict_like\n    arg = self.normalize_dictlike_arg(\"agg\", selected_obj, arg)\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\apply.py\", line 535, in normalize_dictlike_arg\n    raise KeyError(f\"Column(s) {cols_sorted} do not exist\")\nKeyError: \"Column(s) ['timestamp'] do not exist\""}
{"Log_Time": "2024-04-13 14:47:13,451", "Levelname": "ERROR", "Filename": "recommender.py", "Module": "recommender", "Lineno": "256", "FuncName": "Recommendation", "Message": "Error occured while calculating title recommendation for 7: ('KeyError', \"Column(s) ['timestamp'] do not exist\")\nTraceback (most recent call last):\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\ML-Projects\\Movie_Recommender_System\\Recommenders\\recommender.py\", line 242, in get_similar_users\n    user_ratings = similar_user_movies.groupby('title').agg({'rating': 'mean',\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\groupby\\generic.py\", line 1271, in aggregate\n    result = op.agg()\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\apply.py\", line 163, in agg\n    return self.agg_dict_like()\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\apply.py\", line 403, in agg_dict_like\n    arg = self.normalize_dictlike_arg(\"agg\", selected_obj, arg)\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\apply.py\", line 535, in normalize_dictlike_arg\n    raise KeyError(f\"Column(s) {cols_sorted} do not exist\")\nKeyError: \"Column(s) ['timestamp'] do not exist\""}
{"Log_Time": "2024-04-13 14:48:15,327", "Levelname": "ERROR", "Filename": "recommender.py", "Module": "recommender", "Lineno": "255", "FuncName": "Recommendation", "Message": "Error occured while calculating title recommendation for 11: ('KeyError', \"Column(s) ['timestamp'] do not exist\")\nTraceback (most recent call last):\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\ML-Projects\\Movie_Recommender_System\\Recommenders\\recommender.py\", line 242, in get_similar_users\n    user_ratings = similar_user_movies.groupby('title').agg({'rating': 'mean',\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\groupby\\generic.py\", line 1271, in aggregate\n    result = op.agg()\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\apply.py\", line 163, in agg\n    return self.agg_dict_like()\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\apply.py\", line 403, in agg_dict_like\n    arg = self.normalize_dictlike_arg(\"agg\", selected_obj, arg)\n  File \"C:\\Users\\anirban\\PycharmProjects\\Tech_Data\\pyakc\\lib\\site-packages\\pandas\\core\\apply.py\", line 535, in normalize_dictlike_arg\n    raise KeyError(f\"Column(s) {cols_sorted} do not exist\")\nKeyError: \"Column(s) ['timestamp'] do not exist\""}
{"Log_Time": "2024-04-13 14:50:57,525", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "262", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 11"}
{"Log_Time": "2024-04-13 14:51:40,372", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "263", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 11"}
{"Log_Time": "2024-04-13 14:54:44,980", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "264", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 11"}
{"Log_Time": "2024-04-13 14:54:56,506", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "264", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 11"}
{"Log_Time": "2024-04-13 14:56:55,047", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "264", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 15"}
{"Log_Time": "2024-04-13 15:05:59,318", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "264", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 15"}
{"Log_Time": "2024-04-13 15:06:23,655", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "264", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 16"}
{"Log_Time": "2024-04-13 15:06:29,575", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "264", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 11"}
{"Log_Time": "2024-04-13 15:07:06,444", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "264", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 11"}
{"Log_Time": "2024-04-13 15:07:27,494", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "264", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 11"}
{"Log_Time": "2024-04-13 15:07:33,451", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "264", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 15"}
{"Log_Time": "2024-04-13 15:07:39,336", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "264", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 16"}
{"Log_Time": "2024-04-13 15:07:47,134", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "264", "FuncName": "Recommendation", "Message": "15 recommendations generated successfully for 55"}
{"Log_Time": "2024-04-13 15:10:46,396", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "171", "FuncName": "Recommendation", "Message": "15 recommendations generated for Toy Story (1995) successfully!"}
{"Log_Time": "2024-04-13 15:11:50,773", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "171", "FuncName": "Recommendation", "Message": "15 recommendations generated for Toy Story (1995) successfully!"}
{"Log_Time": "2024-04-13 15:14:28,178", "Levelname": "DEBUG", "Filename": "recommender.py", "Module": "recommender", "Lineno": "171", "FuncName": "Recommendation", "Message": "15 recommendations generated for Apocalypse Now (1979) successfully!"}
